backend/__init__.py
backend/authentication/__init__.py
backend/authentication/backend.py
backend/authentication/user.py
backend/routes/index.py

Closes #5 
Implemented JWT user + middleware for authentication. This return `authenticated` scope for every authenticated user, but also `admin` when user have `admin` key `True` in token data. To make endpoint working only for admins, use `@requires(["authenticated", "admin"])` decorator.

JWT Authentication Middleware

---

backend/middleware.py
backend/models/form.py
backend/models/question.py
backend/routes/auth/authorize.py
backend/routes/forms/discover.py
backend/routes/forms/index.py
backend/routes/forms/new.py
backend/routes/forms/submit.py
poetry.lock
pyproject.toml

- Migrated PyMongo to asynchronous Motor.
- Made small fixes in models:
- Removed circular import of Question
- Use cls instead of self (Pydantic stuff)
- Fix form features validation (plain `__members__.values()` don't work).
- For listing views, move data to model before returning to:
- catch broken data
- return `id` instead `_id`
- Locked all forms listing endpoint only to admins.
- Created endpoint for creating new forms (`/forms/new`, POST).
- Closes #6.

Migrate PyMongo to Motor, model fixes and form creation route

---

backend/constants.py
backend/models/__init__.py
backend/models/antispam.py
backend/models/discord_user.py
backend/models/form_response.py
backend/routes/forms/new.py
backend/routes/forms/submit.py
poetry.lock
pyproject.toml

Closes #8 
Created models for form responses, added captcha and blacklist validation and updated user validation. Now also stores data to DB.
Also added duplicate ID validation for forms as side change (found bug when testing).

Form responses storing and validation

---

backend/route_manager.py

This fixes the bug that prevented discoverable from overriding the forms path fragment path.
The issue is specified in [this Notion ticket](https://www.notion.so/pythondiscord/Discoverable-forms-route-does-not-work-91d143070f844376a965856294786f97).
The solution is to sort the route map by whether the URL contains a path fragment (e.g. `/forms/{id:str}`) or not (e.g. `/forms/discoverable`).

Sort routes to have constants first and path fragments last

---

.github/workflows/forms-backend.yml
.github/workflows/status-embed.yml

I've added a `workflow_run`-triggered workflow that reports the status of the `forms-backend.yaml` workflow using a custom status embed. To make sure we have enough information to generate embeds for `pull_request` triggers, the `forms-backend.yaml` file will now upload an artifact with the required information.

Use a custom status embed to report workflow status

---

SCHEMA.md
backend/models/form_response.py
backend/routes/forms/submit.py

Closes this [notion ticket](https://www.notion.so/pythondiscord/Add-Timestamp-To-Responses-b99abd810b6d4dd38e3e4e69e935cda9).
Adds timestamp field to user form responses on model generation.
The model saves an ISO formatted time string to avoid serialization errors. The field is set by the program, even if a user passes the timestamp field.

Adds Timestamp Field

---

.gitignore
backend/__init__.py
backend/constants.py
backend/middleware.py
backend/models/__init__.py
backend/models/form.py
backend/models/form_response.py
backend/routes/auth/authorize.py
backend/routes/forms/discover.py
backend/routes/forms/form.py
backend/routes/forms/index.py
backend/routes/forms/response.py
backend/routes/forms/responses.py
backend/routes/forms/submit.py
backend/routes/index.py
backend/validation.py
poetry.lock
pyproject.toml

This PR introduces OpenAPI specification and Pydantic validation generics to allow for better documenting of our endpoints.
In production documentation will be available through https://forms.pythondiscord.com/docs, with a password protected cookie called `docs_password`.

Provide HTML documentation of endpoints

---

SCHEMA.md
backend/constants.py
backend/models/form.py
backend/routes/forms/form.py
backend/routes/forms/index.py
backend/routes/forms/submit.py
poetry.lock
pyproject.toml

Closes this [notion ticket](https://www.notion.so/pythondiscord/Modify-Patch-Behavior-cf10f8c0fd734e968902359382df2def).
Changes the patch route behavior for dicts, so we don't need to include full objects whenever we update them. Does not affect behavior for other primitives or containers.
Additionally removes the meta object, and moves webhooks under the main form object for the reasons described in the ticket.

Modify Patch Behavior

---

backend/routes/auth/authorize.py

We updated `pyjwt` to version 2.0.0 in #45.
As of that update, [`jwt.encode` returns a string instead of a bytestring](https://github.com/jpadilla/pyjwt/blob/c96131b970fd341106ce33d0a85b50e3bdbb67ec/CHANGELOG.md#jwtencode-return-type), so `.decode`ing the string for the JSON response returned an error.

`jwt.encode` returns a string, not a bytestring.

---

backend/constants.py
backend/routes/auth/authorize.py
backend/routes/forms/submit.py

This PR fixes problems with token security on deploy previews.
The same site attribute would fail on preview branches, as the backend (hosted on the main python discord site), and the request origin (CF or Netlify) were different. This PR simply bypasses that, by setting same site to None on the preview branches.

Fixes SameSite For Deploy Previews

---

backend/routes/admin.py

Adds an endpoint if the environment variable `PRODUCTION` is set to false, which reproduces the behavior of the admin endpoint, without authentication. This is meant to make it easier to get an admin account set up in production without having to manually manipulate the database.

Adds A Dev Only Endpoint For Adding Admins

---

backend/routes/forms/discover.py
backend/routes/forms/form.py

The first thing a developer might want to do when setting up the backend is to add a form. Adding a form requires you have your authorization cookie. Getting your authorization cookie requires clicking the discord OAuth button at the bottom of a form. This creates a sort of chicken-or-egg situation.
This PR aims to resolve that by returning a fake form when the backend contains no forms, and the server is running with the `PRODUCTION` flag set to false.
A better alternative would be to have the DB be created with that form, so we don't have to code in a special case for it, but that didn't seem feasible with mongo. There is no equivalent to something like `init.sql` as far as I could tell.

Empty Authorization Form

---

SCHEMA.md
backend/models/__init__.py
backend/models/question.py
backend/routes/forms/submit.py
backend/routes/forms/unittesting.py

Implements this [notion ticket](https://www.notion.so/pythondiscord/Receive-failed-unittest-submissions-60bc34468996414aacde3c29d7090055).
Adds support for an optional `allow_failures` bool. If true, the backend will only return an error (500) if an internal error occurred. If false, the backend will return an error (403 or 500 depending on failure reason).
This PR also adds a model to aid in parsing the new options.

Allow Unittest Failures

---

backend/routes/forms/submit.py

We store IP hash for anti-spam, however we've so far only being hashing the IPs of our NGINX proxy nodes, meaning the data cannot be used to prevent form abuse. This PR corrects that by instead inspecting the Cf-Connecting-IP header and if set hashing that, otherwise falling back to the remote host.

Fix IP hash

---

backend/models/form.py
backend/routes/forms/form.py

Note that it will make any existing form with an upper case letter impossible to access until its ID is changed, which shouldn't be the case in production according to @HassanAbouelela.

Model: makes Form.id case insensitive

---

backend/routes/forms/submit.py

We currently use WEBHOOK_ENABLED to determine whether user data should be stored to the db. However, when webhooking a form submission this config is ignored, and the user mention is always included if available.
This means that if a user login in using anohter form, and then submits an anonymous form with the same session, their name will be included in the webhook.

Don't include user mention for anonymous form submissions

---

backend/routes/forms/discover.py
backend/routes/forms/form.py
backend/routes/forms/submit.py

Adds a non-discoverable login form in all environments to make it easier to authenticate. This was already available in development, but now it'll always be on the homepage too.
Ideally, we'd have an actual login button, but this is an easy solution in the meantime.

Enable Login Form In Production

---

backend/middleware.py

Hi, I am a Starlette dev. We are trying to discourage usage of BaseHTTPMiddleware.

Replace BaseHTTPMiddleware with pure ASGI middleware

---

backend/models/question.py
backend/routes/forms/unittesting.py
resources/unittest_template.py

Adds the setup method as a special method for unittest question types. Additionally, a couple QoL fixes are included. I changed `unit` to `self` to clarify what it actually is, and I changed an `lstrip` to a `removeprefix` to avoid removing unintentional portions of the name (for instance `something` -> `omething`)
This will require migrating a few database entries by hand, so hold off on merging till that is ready.

Allow Setup For Unittests

---

backend/middleware.py
backend/models/discord_role.py
backend/models/form.py
backend/route_manager.py
poetry.lock
pyproject.toml

Motor version 2.4 is not fully compatible with the version of mongo we're using (we're using latest, which is now 5.0.9 in production, and similar if you recreate your container). Run `docker compose up mongo -d --build` to update.

Bump Motor Version To 3.0.0

---

.github/workflows/forms-backend.yml
Dockerfile

Poetry 1.2 introduced a regression which broke pip `--user` installs. These types of install were the main way we did installations in docker and CI, as they made it much more convenient to control the location, availability, and caching of packages.
Poetry's team does not recognize this as a supported use case, so major changes were required to get everything working again. Most of the changes were consolidated into chrislovering/python-poetry-base for docker, and HassanAbouelela/setup-python for CI.
This is part of a larger movement across all python-discord projects.

Fix Poetry 1.2 Support

---

deployment.yaml

The sentry dsn is now in forms-backend-env instead

Remove sentry-env

---

.github/workflows/sentry-release.yml

https://github.com/tclindner/sentry-releases-action no longer works, this PR migrates to the [official sentry release CI action](https://github.com/getsentry/action-release).

Migration to official Sentry release CI action

---

backend/__init__.py
backend/routes/forms/condorcet.py
poetry.lock
pyproject.toml

Adds an endpoint, `/forms/{form_id}/condorcet/{question_id}` to perform a
Condorcet calculation for the newly added vote components.
Optionally, a `?winners=` parameter can be specified to provide the number of
results to calculate for, defaulting to 1 winner.
The rest of the Condorcet table is provided.
An example response:
``` json
{
"question": {
"id": "vote-1",
"name": "Vote for your preferred options",
"type": "vote",
"data": {
"options": [
"Dog",
"Cat",
"Ferret",
"Worm",
"Chris J Lovering"
]
},
"required": true
},
"winners": [
"Chris J Lovering"
],
"rest_of_table": {
"Dog": {
"wins": [
"Cat",
"Ferret"
],
"losses": []
},
"Cat": {
"wins": [],
"losses": [
"Dog",
"Worm"
]
},
"Ferret": {
"wins": [],
"losses": [
"Dog",
"Worm"
]
},
"Worm": {
"wins": [
"Cat",
"Ferret"
],
"losses": []
}
}
} …
```

Add Condorcet count endpoint

---

backend/authentication/backend.py
backend/authentication/user.py
backend/constants.py
backend/discord.py
backend/routes/auth/authorize.py
backend/routes/discord.py
backend/routes/forms/submit.py
docker-compose.yml
poetry.lock
pyproject.toml

The secret for this is already deployed to the cluster

Use redis for the discord member cache over mongo

---

backend/authentication/backend.py
backend/authentication/user.py
backend/discord.py
backend/routes/discord.py

This is on top of the changes in https://github.com/python-discord/forms-backend/pull/297 so should be merged after.

Use redis to store the role cache
